import './globals.css'
import { Manjari } from 'next/font/google'

const manjari = Manjari({weight: '400', subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manjari.className}>{children}</body>
    </html>
  )
}
